/** @format */

export default {
  login: 'mrsoofi',
  id: 68252647,
  node_id: 'MDQ6VXNlcjY4MjUyNjQ3',
  avatar_url: 'https://avatars.githubusercontent.com/u/68252647?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mrsoofi',
  html_url: 'https://github.com/mrsoofi',
  followers_url: 'https://api.github.com/users/mrsoofi/followers',
  following_url: 'https://api.github.com/users/mrsoofi/following{/other_user}',
  gists_url: 'https://api.github.com/users/mrsoofi/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/mrsoofi/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mrsoofi/subscriptions',
  organizations_url: 'https://api.github.com/users/mrsoofi/orgs',
  repos_url: 'https://api.github.com/users/mrsoofi/repos',
  events_url: 'https://api.github.com/users/mrsoofi/events{/privacy}',
  received_events_url: 'https://api.github.com/users/mrsoofi/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mohammad Soofi',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 1,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2020-07-13T21:29:11Z',
  updated_at: '2021-03-24T11:43:41Z',
};
